language: ruby
rvm:
  - 2.2

addons:
  artifacts:
    s3_region: "us-west-1"
    paths:
      - $(ls spec/integrations/rails_5_2/spec/cypress/*/* | tr "\n" ":")
      - $(ls spec/integrations/rails_4_2/test/cypress/*/* | tr "\n" ":")
      - $(ls spec/integrations/rails_3_2/cypress/*/* | tr "\n" ":")

cache:
  directories:
    - spec/integrations/rails_5_2/spec/node_modules
    - spec/integrations/rails_5_2/vendor/bundle
    - spec/integrations/rails_4_2/test/node_modules
    - spec/integrations/rails_4_2/vendor/bundle
    - spec/integrations/rails_3_2/node_modules
    - spec/integrations/rails_3_2/vendor/bundle

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libxml2-dev

script:
  - bundle exec rake
  - ./spec/integrations/rails_3_2/test.sh
  - ./spec/integrations/rails_4_2/test.sh
  - ./spec/integrations/rails_5_2/test.sh
