language: ruby
rvm:
  - 2.2

#addons:
#  artifacts:
#    s3_region: "ap-southeast-2"
#    paths:
#      - $(ls spec/integrations/*/*/cypress/{screenshots,videos}/* | tr "\n" ":")
#      - $(ls spec/integrations/rails_3_2/cypress/{screenshots,videos}/* | tr "\n" ":")

cache:
  directories:
    - spec/integrations/rails_5_2/spec/node_modules
    - spec/integrations/rails_5_2/vendor/bundle
    - spec/integrations/rails_4_2/test/node_modules
    - spec/integrations/rails_4_2/vendor/bundle
    - spec/integrations/rails_3_2/node_modules
    - spec/integrations/rails_3_2/vendor/bundle

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libxml2-dev
  - sudo apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

script:
  - bundle exec rake
  - ./spec/integrations/rails_3_2/test.sh
  - ./spec/integrations/rails_4_2/test.sh
  - ./spec/integrations/rails_5_2/test.sh
